task:
  name: freebsd-stable
  freebsd_instance:
    image_family: freebsd-12-1
  env:
    RUST_BACKTRACE: 1
  setup_script:
    - pkg install -y curl git
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y
    - . $HOME/.cargo/env
  check_script:
    - . $HOME/.cargo/env
    - cargo check --all-targets --all-features
  build_script:
    - . $HOME/.cargo/env
    - cargo build --all-targets --verbose --all-features
  test_script:
    - . $HOME/.cargo/env
    - cargo test --examples --all-features
    - cargo test --doc --all-features
    - cargo test --lib --all-features
