coverage:
  range: 70..100
  round: down
  precision: 2
  status:
    project:
      default:
        threshold: 2%

# Tests aren't important for coverage
ignore:
  - "tests"

# Make less noisy comments
comment:
  layout: "files"
  require_changes: yes
