on:
  push:
    branches: [master]
  pull_request:
name: cargo test
jobs:
  test:
    runs-on: ubuntu-latest
    name: greenmail/${{ matrix.toolchain }}
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
      - uses: actions/checkout@v2
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
    services:
      greenmail:
        image: greenmail/standalone:1.6.8
        ports:
          - 3025:3025
          - 3110:3110
          - 3143:3143
          - 3465:3465
          - 3993:3993
          - 3995:3995
        env:
          GREENMAIL_OPTS: "-Dgreenmail.setup.test.all -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.auth.disabled -Dgreenmail.verbose"
  test_cyrus:
    runs-on: ubuntu-latest
    name: cyrus/${{ matrix.toolchain }}
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
      - uses: actions/checkout@v2
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features test-full-imap
    services:
      cyrus_imapd:
        image: outoforder/cyrus-imapd-tester:latest
        ports:
          - 3025:25
          - 3143:143
          - 3465:465
          - 3993:993
